### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by qiaokang0** [MG2033/MobileNet-V2#6]
I try the code and get the runtime error down,any idea?

Training...
Epoch-0-:   0%|                                         | 0/391 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 46, in <module>
    main()
  File "main.py", line 34, in main
    trainer.train()
  File "/home/qiaokang/MobileNet-V2-master/train.py", line 63, in train
    cur_loss.backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

**Comment by ddhgiang** [comment]
also got the same problem

**Comment by nuptwuchen** [comment]
same problem

**Comment by MG2033** [comment]
Which Pytorch version do you use?

**Comment by nekulkarni** [comment]
I got the same error with Pytorch 0.4.1. 

> Training...
Epoch-0-:   0%|                                                                                                         | 0/391 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main()
  File "main.py", line 33, in main
    trainer.train()
  File "/home/grafty/external_projects/pruning/MobileNet-V2/train.py", line 63, in train
    cur_loss.backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

**Comment by nekulkarni** [comment]
**Update:**  worked for me when I used pytorch 0.3.0. The error no longer came up.

**Comment by feixuedudiao** [comment]
what the checkpoint name,and where can download it?

**Comment by jehovahxu** [comment]
it worked when I used pytorch 0.3.1 but i was not found the change in pytorch 0.4.x

**Comment by lcj1105** [comment]
i also got the same problem in pyTorch 0.4.0

**Comment by jehovahxu** [comment]
> i also got the same problem in pyTorch 0.4.0

changing your dropout or relu6 to out-of-place or use the model of [https://github.com/tonylins/pytorch-mobilenet-v2]()

**Comment by lcj1105** [comment]
> > i also got the same problem in pyTorch 0.4.0
> 
> changing your dropout or relu6 to out-of-place or use the model of https://github.com/tonylins/pytorch-mobilenet-v2

thanks !  When I did this, the problem was solved.

**Comment by BlueBubbleWei** [comment]
search the keyword "inplace" in train.py and delete the args like inplace=True,or change inplace=False,I solved the problem,it's a pytorch version problem,the author used version 0.4,and yours in version 0.4.
